### ISSUE TITLE
Feature Request: add support for Open Folder

### ISSUE THREAD

**Issue by eauxpie** [mayerwin/vs-customize-window-title#80]
When using Cmake directly with Visual Studio's Open Folder functionality, it is impossible to use this extension to customize the title bar, because there is no active solution and the `Document open` and `No document or solution open` cases do not apply.

**Comment by sapien2** [comment]
I can report that the  [gitBranchName] tag does not work in this mode.

**Comment by mayerwin** [comment]
@sapien2 Turns out that Open Folder mode makes the solution to be the folder itself rather than a subfile. I fixed the code in 5.4.1 released today to handle this special case better. [gitBranchName] should work now. Thanks for the bug report!
@eauxpie It should work equally well as when not in Open Folder mode. If you identify issues, please provide a minimal test repo.

As a side note, when encountering issues, a workaround can sometimes be to use a XML file to hardcode some variables.

**Comment by sapien2** [comment]
@mayerwin, it is working even worse now. The branch name is glued to the dir name without any separator, but the  [gitBranchName] tag still do not work.

<img width="1174" height="683" alt="Image" src="https://github.com/user-attachments/assets/05e34c6e-29ed-4c4d-ade7-1ea0f67c768c" />

**Comment by mayerwin** [comment]
@sapien2 The branch name is glued as you've not put any space between [ideName] and [gitBranchName] (in Solution in design mode).
Also, you should not set [gitBranchName] as the Appended string. The default is just a tab (	). This parameter is only to make it possible for the extension to identify if other VS instances have had their title rewritten as well. Tags in this parameter are not replaced with their values.
Can you double check the extension really updated to the latest version (5.4.1)?

**Comment by mayerwin** [comment]
You can also try to disable compact mode for the title bar in the VS settings to see if it changes something (in compact mode, it'll replace [- [ideName]] with an empty string). I tested on my end (just open an empty folder and create a git repo inside) and it works in compact and non-compact mode.

**Comment by sapien2** [comment]
It works as expected now. Thank you for the fix.

<img width="995" height="592" alt="Image" src="https://github.com/user-attachments/assets/10cf862f-fd3d-4b4d-8a39-a3cea24fa27b" />
